# Generated by Django 4.1 on 2022-08-22 05:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_community_transport_user_birth_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Emoji',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='UserEmoji',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('datetime', models.DateTimeField()),
                ('emoji', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.emoji')),
            ],
        ),
    ]
