# Generated by Django 4.1 on 2022-08-22 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_useremoji_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useremoji',
            name='datetime',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
