# Generated by Django 4.1 on 2022-08-24 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_useremoji_datetime'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useremoji',
            name='datetime',
        ),
        migrations.AddField(
            model_name='useremoji',
            name='date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
