# Generated by Django 4.1 on 2022-08-24 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_remove_useremoji_datetime_useremoji_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useremoji',
            name='date',
            field=models.DateField(null=True),
        ),
    ]
