# Generated by Django 4.1 on 2022-08-30 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_useremoji_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='useremoji',
            name='comment',
            field=models.TextField(null=True),
        ),
    ]
