# Generated by Django 4.1 on 2022-09-30 05:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useremoji',
            name='comment',
        ),
    ]
