# Generated by Django 4.1 on 2022-10-05 06:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_remove_useremoji_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useremoji',
            name='name',
        ),
    ]
